// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX_ld0JqHk_GGYdL2kVYo3R33HL9aqM6g',
    appId: '1:18218463208:web:5c395e96279aa80ab33e5d',
    messagingSenderId: '18218463208',
    projectId: 'flutter-8903b',
    authDomain: 'flutter-8903b.firebaseapp.com',
    storageBucket: 'flutter-8903b.firebasestorage.app',
    measurementId: 'G-ZMV0L12V8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwoXLMBdb5MeKU1nA1cy2lLji184jZ_Zk',
    appId: '1:18218463208:android:b7ddadf2f9ef5f3db33e5d',
    messagingSenderId: '18218463208',
    projectId: 'flutter-8903b',
    storageBucket: 'flutter-8903b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHxj_GJAkf5kJLyodanan3LofoQV49tcQ',
    appId: '1:18218463208:ios:c8e98b1fc23330c6b33e5d',
    messagingSenderId: '18218463208',
    projectId: 'flutter-8903b',
    storageBucket: 'flutter-8903b.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHxj_GJAkf5kJLyodanan3LofoQV49tcQ',
    appId: '1:18218463208:ios:c8e98b1fc23330c6b33e5d',
    messagingSenderId: '18218463208',
    projectId: 'flutter-8903b',
    storageBucket: 'flutter-8903b.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX_ld0JqHk_GGYdL2kVYo3R33HL9aqM6g',
    appId: '1:18218463208:web:671f7500aef79281b33e5d',
    messagingSenderId: '18218463208',
    projectId: 'flutter-8903b',
    authDomain: 'flutter-8903b.firebaseapp.com',
    storageBucket: 'flutter-8903b.firebasestorage.app',
    measurementId: 'G-NFYYH00XWM',
  );
}
